// Generated by CoffeeScript 1.10.0
var Kefir, KefirBus, deepAssign, makeCollectionStream;

Kefir = require('kefir');

KefirBus = require('kefir-bus');

deepAssign = require('deep-assign');

module.exports = makeCollectionStream = function(items) {
  var _collection$, collection$;
  _collection$ = KefirBus();
  collection$ = _collection$.toProperty();
  collection$.emit = _collection$.emit;
  collection$.onValue(function(_items) {
    return collection$.last_items = _items;
  });
  collection$.item$s = {};
  collection$.getItem = function(item_id) {
    var _item$, item$;
    if (!(item$ = collection$.item$s[item_id])) {
      _item$ = KefirBus();
      item$ = _item$.toProperty();
      item$.emit = _item$.emit;
      item$.onValue(function() {});
      collection$.item$s[item_id] = item$;
    }
    return item$;
  };
  collection$.setItem = function(item_id, item) {
    var item$;
    item$ = collection$.getItem(item_id);
    item$.emit(item);
    return item$;
  };
  collection$.updateItem = function(item_id, update) {
    var item, item$;
    items = collection$.last_items;
    item = items.filter(function(item) {
      return item._id === item_id;
    })[0];
    if (item == null) {
      return;
    }
    deepAssign(item, update);
    item$ = collection$.getItem(item_id);
    collection$.emit(items);
    item$.emit(item);
    return item$;
  };
  collection$.createItem = function(new_item) {
    items = collection$.last_items;
    items.push(new_item);
    collection$.emit(items);
    return collection$.setItem(new_item._id, new_item);
  };
  collection$.removeItem = function(item_id) {
    items = collection$.last_items;
    items = items.filter(function(item) {
      return item._id !== item_id;
    });
    collection$.emit(items);
    return collection$;
  };
  collection$.emit(items);
  items.map(function(item) {
    var item$;
    return item$ = collection$.setItem(item._id, item);
  });
  return collection$;
};
