// Generated by CoffeeScript 1.10.0
var Kefir, KefirBus, deepAssign, makeCollectionStream;

Kefir = require('kefir');

KefirBus = require('kefir-bus');

deepAssign = require('deep-assign');

module.exports = makeCollectionStream = function(items) {
  var collection$;
  collection$ = KefirBus();
  collection$.onValue(function(_items) {
    return collection$.last_items = _items;
  });
  collection$.item$s = {};
  collection$.getItem$ = function(item_id) {
    var item$;
    if (!(item$ = collection$.item$s[item_id])) {
      item$ = KefirBus();
      collection$.item$s[item_id] = item$;
    }
    return item$;
  };
  collection$.updateItem = function(item_id, update) {
    var item, item$;
    items = collection$.last_items;
    item = items.filter(function(item) {
      return item._id === item_id;
    })[0];
    if (item == null) {
      return;
    }
    deepAssign(item, update);
    item$ = collection$.getItem$(item_id);
    collection$.emit(items);
    return item$.emit(item);
  };
  collection$.createItem = function(new_item) {
    items = collection$.last_items;
    items.push(new_item);
    collection$.emit(items);
    return collection$.getItem$(new_item._id);
  };
  collection$.removeItem = function(item_id) {
    items = collection$.last_items;
    items = items.filter(function(item) {
      return item._id !== item_id;
    });
    return collection$.emit(items);
  };
  collection$.emit(items);
  return collection$;
};
